# """
# Django settings for VisionCart project.

# Generated by 'django-admin startproject' using Django 6.1.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.1/ref/settings/
# """

# from pathlib import Path


# # =========================================================
# # BASE DIRECTORY
# # =========================================================

# BASE_DIR = Path(__file__).resolve().parent.parent


# # =========================================================
# # SECURITY SETTINGS
# # =========================================================

# SECRET_KEY = 'django-insecure-ykd^$k_6f$^l*xp4dniccx%sj5f*a(8%5+2%7bfas1@vs0n+yo'

# DEBUG = True

# ALLOWED_HOSTS = []


# # =========================================================
# # APPLICATION DEFINITION
# # =========================================================

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',

#     'accounts',
#     'orders',
#     'store',
# ]


# # =========================================================
# # MIDDLEWARE
# # =========================================================

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',

#     'django.contrib.sessions.middleware.SessionMiddleware',

#     'django.middleware.common.CommonMiddleware',

#     'django.middleware.csrf.CsrfViewMiddleware',

#     'django.contrib.auth.middleware.AuthenticationMiddleware',

#     # VisionCart session and cache protection.
#     'VisionCart.middleware.VisionCartSecurityMiddleware',

#     'django.contrib.messages.middleware.MessageMiddleware',

#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]


# # =========================================================
# # URL CONFIGURATION
# # =========================================================

# ROOT_URLCONF = 'VisionCart.urls'


# # =========================================================
# # TEMPLATES
# # =========================================================

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',

#         'DIRS': [
#             BASE_DIR / "templates",
#         ],

#         'APP_DIRS': True,

#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]


# # =========================================================
# # WSGI
# # =========================================================

# WSGI_APPLICATION = 'VisionCart.wsgi.application'


# # =========================================================
# # DATABASE
# # =========================================================

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # =========================================================
# # PASSWORD VALIDATION
# # =========================================================

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': (
#             'django.contrib.auth.password_validation.'
#             'UserAttributeSimilarityValidator'
#         ),
#     },
#     {
#         'NAME': (
#             'django.contrib.auth.password_validation.'
#             'MinimumLengthValidator'
#         ),
#     },
#     {
#         'NAME': (
#             'django.contrib.auth.password_validation.'
#             'CommonPasswordValidator'
#         ),
#     },
#     {
#         'NAME': (
#             'django.contrib.auth.password_validation.'
#             'NumericPasswordValidator'
#         ),
#     },
# ]


# # =========================================================
# # INTERNATIONALIZATION
# # =========================================================

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # =========================================================
# # STATIC FILES
# # =========================================================

# # =========================================================
# # STATIC AND MEDIA FILES
# # =========================================================

# STATIC_URL = "/static/"

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"
# # =========================================================
# # CUSTOM USER MODEL
# # =========================================================

# AUTH_USER_MODEL = "accounts.User"


# # =========================================================
# # SESSION SECURITY
# # =========================================================

# # Destroy the browser session when the browser is closed.
# #
# # This prevents the authentication session from being
# # intentionally kept as a persistent browser cookie.
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# # =========================================================
# # EMAIL
# # =========================================================

# MAILERS = {
#     'default': {
#         'BACKEND': 'django.core.mail.backends.console.EmailBackend',
#     },
# }


"""
Django settings for VisionCart project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# =========================================================
# SECURITY SETTINGS
# =========================================================

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-local-development-only-key",
)

DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]


# =========================================================
# APPLICATION DEFINITION
# =========================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts",
    "orders",
    "store",
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "VisionCart.middleware.VisionCartSecurityMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = "VisionCart.urls"


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = "VisionCart.wsgi.application"


# =========================================================
# DATABASE
# =========================================================

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


# =========================================================
# MEDIA FILES
# =========================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# =========================================================
# CUSTOM USER MODEL
# =========================================================

AUTH_USER_MODEL = "accounts.User"


# =========================================================
# SESSION SECURITY
# =========================================================

SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# =========================================================
# EMAIL
# =========================================================

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


# =========================================================
# CSRF / DEPLOYMENT
# =========================================================

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]


# =========================================================
# PRODUCTION SECURITY
# =========================================================

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True