# Generated by Django 6.1.1 on 2026-09-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('DUMMY', 'Dummy Online Payment')], max_length=10),
        ),
    ]
